# Required for `uv`.
# See https://github.com/dependabot/dependabot-core/issues/10478#issuecomment-2691330949.
enable-beta-ecosystems: true
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
